### ISSUE TITLE
Australia: Fetch/load process creates duplicate records

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocdsdata#145]
The Australia API has two endpoints: search API, which returns a list of releases but with a limited set of fields, and individual object API, which returns a single release with all fields (see [API docs](https://github.com/NSW-eTendering/NSW-eTendering-API/wiki)).

The scraper queries the search endpoint, then uses the ids from each of the search results to query the individual endpoint to get all the fields for each release in the results.

However the load process then saves to the database **both** the release from the search API (with it's limited set of fields) **and** the release from the individual object API (with all the fields)

So we end up with lots of kind of half duplicate records in the database.

My current work around for this is to filter on the filename to exclude results which look like they came from the search API from my queries, e.g.

 ```WHERE filename NOT LIKE 'type-%'```

It's a bit of an unusual set up but I think we should only be saving the results from the individual object APIs to the database.

**Comment by odscjames** [comment]
There are 2 things here:

> It's a bit of an unusual set up but I think we should only be saving the results from the individual object APIs to the database.

If I'm understanding correctly, this should be an easy fix. Already in the framework, if you declare a file type something that starts with "meta" then it won't be saved to the DB (See Ukraine). So all the "type-" files, I just have to make their type a meta type.

> Also, there appears to be a discrepancy between the number of releases returned by the search APIs and the number of releases fetched from the individual object APIs, e.g. COUNT(DISTINCT release_id) returns:

I'm going to have to think through this one. (Cos I'm not clear why they should be the same at first reading.) But also remember we stopped this load before the fetch had totally finished, so that might account for it.

**Comment by duncandewhurst** [comment]
thanks @odscjames, the easy fix sounds right to me

regarding the release counts, I think they should be the same, since the individual APIs are called based on the results from the search API, but had forgotten we stopped it part way through so that may well explain it.
